security:
  oauth2:
    client:
      clientId: ****
      clientSecret: ****
      accessTokenUri: https://graph.facebook.com/login/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graphs.facebook.com/